title = 'Laurie Li'
theme = 'gallery'
defaultTheme = 'dark'

# Author config
[author]
    name = "Laurie Li"
    email = "laurieliyang@outlook.com"
    link = "https://www.laurieli.com"

# Theme params
[params]
    defaultTheme = 'dark'

[params.page.share]
    enable = false

[params.carouselHomepage] 
    enable = false

[menus]

    # main menu
    [[menus.main]]
        name = 'Home 主页'
        pageRef= '/'
    [[menus.main]]
        name = 'Travel 旅行'
        pageRef= '/travel'

    # footer menu
    [[menus.footer]]
        name = 'Home'
        pageRef = '/'
    [[menus.footer]]
        name = 'Travel'
        pageRef= '/travel'